### ISSUE TITLE
Notice on every puppet run

### ISSUE THREAD

**Issue by MACscr** [devopera/puppet-docsf#1]
Why is there a need to create a notice every time puppet is ran?

root@charts:~/csf# puppet agent -t --verbose
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for charts.mon.foo.com
Info: Applying configuration version '1422823843'
Notice: /Stage[main]/Docsf/Exec[enter-class-csf]/returns: ConfigServer initially installed? true
Notice: /Stage[main]/Docsf/Exec[enter-class-csf]/returns: executed successfully
Notice: /Stage[main]/Docsf/Exec[install_maldet_cleanup]/returns: executed successfully
Notice: /Stage[main]/Docsf/Package[libtime-hires-perl]/ensure: ensure changed 'purged' to 'present'
Notice: Finished catalog run in 2.23 seconds

**Comment by cleverlight** [comment]
You're right.  There's not.  I've removed it.
